/* tslint:disable */
/* eslint-disable */
/**
 * vuefast-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Priority } from './Priority';
import {
    PriorityFromJSON,
    PriorityFromJSONTyped,
    PriorityToJSON,
} from './Priority';

/**
 * 
 * @export
 * @interface CreateTodoRequest
 */
export interface CreateTodoRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTodoRequest
     */
    title: string;
    /**
     * 
     * @type {Priority}
     * @memberof CreateTodoRequest
     */
    priority?: Priority | null;
}

/**
 * Check if a given object implements the CreateTodoRequest interface.
 */
export function instanceOfCreateTodoRequest(value: object): value is CreateTodoRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateTodoRequestFromJSON(json: any): CreateTodoRequest {
    return CreateTodoRequestFromJSONTyped(json, false);
}

export function CreateTodoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTodoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'priority': json['priority'] == null ? undefined : PriorityFromJSON(json['priority']),
    };
}

export function CreateTodoRequestToJSON(value?: CreateTodoRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'priority': PriorityToJSON(value['priority']),
    };
}

