/* tslint:disable */
/* eslint-disable */
/**
 * vuefast-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Priority = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type Priority = typeof Priority[keyof typeof Priority];


export function instanceOfPriority(value: any): boolean {
    for (const key in Priority) {
        if (Object.prototype.hasOwnProperty.call(Priority, key)) {
            if ((Priority as Record<string, Priority>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PriorityFromJSON(json: any): Priority {
    return PriorityFromJSONTyped(json, false);
}

export function PriorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Priority {
    return json as Priority;
}

export function PriorityToJSON(value?: Priority | null): any {
    return value as any;
}

